### ISSUE TITLE
sa ocflex nabr

### ISSUE THREAD

**Issue by babajoeltdsti** [aflextr/dizipal-stremio-addon#1]
git

**Comment by babajoeltdsti** [comment]
ZAZAZAZAZAZAZAZAZAZAZZA XDDDDDDDDDDDDDDDDD BRUHHHHHHHSHHHHEHHHHHHHXHHHHHH

**Comment by aflextr** [comment]
dava edildiniz.

**Comment by babajoeltdsti** [comment]
lan surtk nie konumu kapattınpc

**Comment by babajoeltdsti** [comment]
benim sorunum çözülmedi

**Comment by aflextr** [comment]
> benim sorunum çözülmedi

senin sorununu zenciler çözer.
