### ISSUE TITLE
Eklentide muhtemel bağlantı sorunu

### ISSUE THREAD

**Issue by yangkoson** [aflextr/dizipal-stremio-addon#2]
Steamio üzerinden dizipal içeriklerinin hiçbirini çekmiyor. Gibi ve Prens gibi başlıkları aratarak denedim. Acaba şu an bir problem mi var?

**Comment by aflextr** [comment]
> Steamio üzerinden dizipal içeriklerinin hiçbirini çekmiyor. Gibi ve Prens gibi başlıkları aratarak denedim. Acaba şu an bir problem mi var?

Film ya da diziyi arattığınızda aşağıya kaydırdığınızda çıkması lazım

**Comment by Bugrakca** [comment]
Telefondan da denedim, pc den de denedim fakat calismiyor. Dizipal'a ait bir bolum yok.
