### ISSUE TITLE
Eklenti calismiyor

### ISSUE THREAD

**Issue by Bugrakca** [aflextr/dizipal-stremio-addon#5]
"Dizi ya da Film aratin asagi kaydirin geliyor" yaziyor fakat basarili olamadim. Bir sorun olma ihtimali olabilir mi? Hem pc de hem de mobilde denedim sonuc alamadim.

Edit: Az önce televizyondan denedim. Gelir gibi yapıyor ama kayboluyor. 

Tesekkurler.

**Comment by aflextr** [comment]
> "Dizi ya da Film aratin asagi kaydirin geliyor" yaziyor fakat basarili olamadim. Bir sorun olma ihtimali olabilir mi? Hem pc de hem de mobilde denedim sonuc alamadim.
> 
> Edit: Az önce televizyondan denedim. Gelir gibi yapıyor ama kayboluyor.
> 
> Tesekkurler.

Dizipalin Adresi 2 haftada bir güncellendiği için veriyi çekmekte sıkıntı yaşıyor o yüzden eklenti çalışamama durumları oluşabiliyor. Şuanda yayınladığım güncelleme ile sorunun düzelmesi lazım
