### ISSUE TITLE
Stremio'ya katalog gelmiyor

### ISSUE THREAD

**Issue by aliyilma** [aflextr/dizipal-stremio-addon#6]
Öncelikle bu eklenti için teşekkürler. Stremio'ya eklentinin başarı ile kurulduğunu görüyorum fakat ne ana sayfada ne de arama yaptıktan sonra eklenti'ye/dizipal'a ait sonuçları göremiyorum.
<img width="1440" alt="Ekran Resmi 2024-11-15 02 54 25" src="https://github.com/user-attachments/assets/e8522541-c107-4436-9b80-e8cd144ddb5a">
<img width="1440" alt="Ekran Resmi 2024-11-15 02 55 07" src="https://github.com/user-attachments/assets/55318861-9aa9-4864-9f54-80169e6eafb7">
<img width="1440" alt="Ekran Resmi 2024-11-15 02 56 02" src="https://github.com/user-attachments/assets/c180a670-50c9-4b20-822b-ff605d1a9cd6">

**Comment by aflextr** [comment]
Dizipalin Adresi 2 haftada bir güncellendiği için veriyi çekmekte sıkıntı yaşıyor o yüzden eklenti çalışamama durumları oluşabiliyor. Şuanda yayınladığım güncelleme ile sorunun düzelmesi lazım.

**Comment by aliyilma** [comment]
Evet düzelmiş şakır şakır çalışıyor. Çok teşekkürler, emeğinize sağlık :)
