### ISSUE TITLE
url changed on source :)

### ISSUE THREAD

**Issue by washeree** [aflextr/dizipal-stremio-addon#7]
Selamlar, kaynak url sürekli değiştiği için sorun olduğunu bildiğimden local'a alıp bir bakmak istedim. Daha önce addon deneyimin olmamıştı fakat historyden bakıp değişiklikleri yaptığımda arama kısmında yinede sonuç göremedim. Vaktiniz olduğunda bir göz atar mısınız? Teşekkürler.

**Comment by aflextr** [comment]
Dizipalin adresi değişmemiş ve eklenti çalışıyor bende

**Comment by washeree** [comment]
tekrar selamlar, uzun zaman oldu aslında eklentiyi ekleyeli ve çalışmamıştı, bende bir kodlara göz gezdireyim istedim, sizin kodlarınızda .env içinde ...843 yazıyor dün siteyi aradığımda 823 olarak karşıma çıkmıştı. Şimdi 843e tıkladım gerçekten çalışıyor. Bende arama sonuçları bu şekilde desktop app ve tv de, altını kestim nfsw içerikte çıkıyor diye. Şu an kafam karıştı açıkcası. 
![Ekran görüntüsü 2024-12-16 100901](https://github.com/user-attachments/assets/1faccbc1-c9a3-4171-85d3-6c8a7ba0a109)

**Comment by washeree** [comment]
Hatta şimdi bir de vpn ile denedim acaba yurtdışından bağlanınca değişir mi diye fakat sonuç aynı.

**Comment by washeree** [comment]
Sorunu çözdüm, işleri değil İşleri yazınca çıkıyor. Javascript bilmediğim için case sensitive fonksiyonunu aşmanın bir yolu var mıdır?

**Comment by aflextr** [comment]
> Sorunu çözdüm, işleri değil İşleri yazınca çıkıyor. Javascript bilmediğim için case sensitive fonksiyonunu aşmanın bir yolu var mıdır?

Belki ileriki zamanda bakılabilir
